server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1054020609574-1hvkvqvuf2gklovnjae39m1hfcme7sl3.apps.googleusercontent.com
            client-secret: HLB8mKm_A62CCKhSIgTzQoXr
            scope:
            - email
            - profile
            
          facebook:
            client-id: 577078206996719
            client-secret: d21b77d52ef891c559cc45af32d97002
            scope:
            - email
            - public_profile
            
          naver:
            client-id: qHu_kSd83pEJqvuS9nMg
            client-secret: MSbvsaAV_o
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code # 코드를 받는다
            redirect-uri: http://localhost:8000/login/oauth2/code/naver # 콜백 주소
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 로그인 창이 뜸
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰 받기
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보 받기
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
            
            
            
            
                        